<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="2" failures="1" errors="0" time="1.076">
  <testsuite name="PatientContext" errors="0" failures="1" skipped="0" timestamp="2024-11-15T22:49:09" time="0.574" tests="2">
    <testcase classname="PatientContext provides the correct context values" name="PatientContext provides the correct context values" time="0.013">
      <failure>TypeError: expect(...).toHaveTextContent is not a function
    at Object.toHaveTextContent (/Users/alex/Documents/VillageVetTestingRound2/client/src/context/PatientContext.test.js:35:52)
    at Promise.then.completed (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at _runTest (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/alex/Documents/VillageVetTestingRound2/node_modules/jest-runner/build/testWorker.js:106:12)</failure>
    </testcase>
    <testcase classname="PatientContext throws an error when usePatient is used outside of a PatientProvider" name="PatientContext throws an error when usePatient is used outside of a PatientProvider" time="0.013">
    </testcase>
  </testsuite>
</testsuites>